image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
#  - deploy


maven-build:
  image: maven:3.8.5-openjdk-17
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar
  only:
    - tags


docker-build:
  stage: package
  script:
    - docker build -t ${REGISTRY_HOST}/base-kotlin-project .
    - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
    - docker push ${REGISTRY_HOST}/base-kotlin-project:${CI_COMMIT_TAG}
    - docker logout ${REGISTRY_HOST}
  only:
    - tags