image: docker:latest
services:
  - docker:dind

stages:
  - test
  - build
  - package
#  - deploy

test-variables:
  stage: test
  needs: []
  script:
    - echo "${CI_COMMIT_TAG}"
    - echo "${REGISTRY_HOST}"
    - echo "${REGISTRY_USERNAME}"
    - echo "${REGISTRY_PASSWORD}"


maven-build:
  image: maven:3.8.5-openjdk-17
  stage: build
  needs: ["test-variables"]
  script: "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar
  only:
    - tags

docker-build:
  stage: package
  needs: ["maven-build"]
  script:
    - docker build -t ${REGISTRY_HOST}/base-kotlin-project:${CI_COMMIT_TAG} .
    - docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
    - docker push ${REGISTRY_HOST}/base-kotlin-project:${CI_COMMIT_TAG}
    - docker logout ${REGISTRY_HOST}
  only:
    - tags