image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
#  - deploy


maven-build:
  image: maven:3.8.5-openjdk-17
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar


docker-build:
  stage: package
  script:
    - docker build -t 192.168.3.20:8088/base-kotlin-project .
    - docker login -u deploy -p deploy 192.168.3.20:8088
    - docker push 192.168.3.20:8088/base-kotlin-project
    - docker logout 192.168.3.20:8088